## 
## Travis Unit Testing settings
##

## There are no unit tests currently aviable, except some debugging tests on main.cpp (Unstable and susceptible to be modified
## or even broken). Since this is a C++ metaprogramming library, successfull compilation is interpreted as the tests successfully
## passed (If not, the static asserts fail and the compilation fails). 

language: cpp
compiler:
  - clang

before_install:
  # g++
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # libc++
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9.1"; fi

  # libc++
  - if [ "$CXX" == "clang++" ]; then cwd=$(pwd); fi #PUSH
  - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-std=c++0x -stdlib=libc++"; fi
  - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
  - if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
  - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi #POP
  
  # install biicode:
  - wget https://s3.amazonaws.com/biibinaries/release/1.3.3/bii-ubuntu32_1_3_3.deb 
  - (! sudo dpkg -i bii-ubuntu32_1_3_3.deb ) && sudo apt-get -f install

script: 
  # Show me what compiler are you using:
  - echo $CC $CXX
  - $CXX --version
  
  - bii find
  - bii work
  - bii cpp:build
  - ./bin/manu343726_turbo_main_main 
